name: Generate Snake

on:
schedule:
- cron: "0 0 * * *"
workflow_dispatch:

permissions:
contents: write

jobs:
build:
runs-on: ubuntu-latest


steps:
  - uses: actions/checkout@v3

  - uses: Platane/snk@v3
    with:
      github_user_name: ${{ github.repository_owner }}

      outputs: |
        dist/github-contribution-grid-snake-dark.svg?color_snake=%239330FF&color_dots=%230D1117,%232D0A52,%234B0082,%236A0DAD,%239330FF
        dist/github-contribution-grid-snake.svg?color_snake=%239330FF

  - uses: crazy-max/ghaction-github-pages@v3.1.0
    with:
      target_branch: output
      build_dir: dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

